"""
Base strategy class that all investment strategies inherit from
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any, Tuple
import pandas as pd
from datetime import datetime
from dataclasses import dataclass
from enum import Enum


class SignalType(Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class TradingSignal:
    """Represents a trading signal generated by a strategy"""
    symbol: str
    signal: SignalType
    confidence: float  # 0.0 to 1.0
    price: float
    quantity: Optional[float] = None
    timestamp: datetime = None
    reason: str = ""
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.metadata is None:
            self.metadata = {}


class BaseStrategy(ABC):
    """
    Base class for all investment strategies
    """
    
    def __init__(self, name: str, parameters: Dict[str, Any] = None):
        self.name = name
        self.parameters = parameters or {}
        self.is_active = True
        
        # Performance tracking
        self.total_signals = 0
        self.successful_signals = 0
        self.failed_signals = 0
        
        # Risk management
        self.max_position_size = self.parameters.get('max_position_size', 10.0)
        self.stop_loss_percentage = self.parameters.get('stop_loss_percentage', 5.0)
        self.take_profit_percentage = self.parameters.get('take_profit_percentage', 15.0)
    
    @abstractmethod
    def generate_signals(self, data: pd.DataFrame, symbol: str) -> List[TradingSignal]:
        """
        Generate trading signals based on market data
        
        Args:
            data: Historical price data with OHLCV columns
            symbol: Stock symbol
            
        Returns:
            List of trading signals
        """
        pass
    
    @abstractmethod
    def get_required_indicators(self) -> List[str]:
        """
        Return list of technical indicators required by this strategy
        """
        pass
    
    def validate_data(self, data: pd.DataFrame) -> bool:
        """
        Validate that the data contains required columns and indicators
        """
        required_columns = ['Open', 'High', 'Low', 'Close', 'Volume']
        required_indicators = self.get_required_indicators()
        
        # Check basic OHLCV columns
        for col in required_columns:
            if col not in data.columns:
                return False
        
        # Check required indicators
        for indicator in required_indicators:
            if indicator not in data.columns:
                return False
        
        # Check minimum data points
        if len(data) < self.parameters.get('min_data_points', 50):
            return False
        
        return True
    
    def calculate_position_size(self, portfolio_value: float, confidence: float) -> float:
        """
        Calculate position size based on portfolio value and signal confidence
        """
        base_size = min(self.max_position_size, portfolio_value * 0.1)  # Max 10% of portfolio
        adjusted_size = base_size * confidence  # Adjust by confidence
        return max(adjusted_size, portfolio_value * 0.01)  # Minimum 1% position
    
    def should_stop_loss(self, entry_price: float, current_price: float, signal_type: SignalType) -> bool:
        """
        Check if stop loss should be triggered
        """
        if signal_type == SignalType.BUY:
            loss_percentage = (entry_price - current_price) / entry_price * 100
            return loss_percentage >= self.stop_loss_percentage
        elif signal_type == SignalType.SELL:
            loss_percentage = (current_price - entry_price) / entry_price * 100
            return loss_percentage >= self.stop_loss_percentage
        
        return False
    
    def should_take_profit(self, entry_price: float, current_price: float, signal_type: SignalType) -> bool:
        """
        Check if take profit should be triggered
        """
        if signal_type == SignalType.BUY:
            profit_percentage = (current_price - entry_price) / entry_price * 100
            return profit_percentage >= self.take_profit_percentage
        elif signal_type == SignalType.SELL:
            profit_percentage = (entry_price - current_price) / entry_price * 100
            return profit_percentage >= self.take_profit_percentage
        
        return False
    
    def update_performance(self, signal_successful: bool):
        """
        Update strategy performance metrics
        """
        self.total_signals += 1
        if signal_successful:
            self.successful_signals += 1
        else:
            self.failed_signals += 1
    
    def get_win_rate(self) -> float:
        """
        Get the win rate of the strategy
        """
        if self.total_signals == 0:
            return 0.0
        return self.successful_signals / self.total_signals
    
    def get_strategy_info(self) -> Dict[str, Any]:
        """
        Get strategy information and parameters
        """
        return {
            'name': self.name,
            'parameters': self.parameters,
            'is_active': self.is_active,
            'total_signals': self.total_signals,
            'successful_signals': self.successful_signals,
            'failed_signals': self.failed_signals,
            'win_rate': self.get_win_rate(),
            'required_indicators': self.get_required_indicators()
        }